open-chaos/experiment-catalog

file-must-not-disappear/README.md
=> Added initial documentation for one experiment.

.gitignore, file-must-not-disappear/README.md, file-must-not-disappear/file-must-not-disappear.json
=> Added params for simple experiment

file-must-not-disappear/README.md
=> Fixed docker experiment execution

README.md
=> Added catalog content format instructions

drain-node/README.md, kill-pods/README.md
=> added readme for pod experiments

delete=all-nodes/README.md, delete=all-nodes/delete-all-nodes.json, kill-microservice/README.md, kill-microservice/kill-microservice.json
=> added kill microservice

delete-all-nodes/README.md, delete-all-nodes/delete-all-nodes.json
=> added delete all nodes catalog entry #29

delete-named-node/README.md, delete-named-node/delete-named-node-exeriment.json
=> added delete named node

drain-node/README.md, kill-pods/README.md
=> Changed to chaostoolkit docker image

spring-boot-latency/README.md, spring-boot-latency/introduce-latency-experiment.json
=> Added latency based Spring Boot experiment

delete-random-node/README.md, delete-random-node/delete-random-node-experiment.json
=> added delete random node

azure-aks-stop-random-node/README.md, azure-aks-stop-random-node/stop-random-node-experiment.json
=> added azure aks stop node

azure-aks-stop-random-node/README.md
=> corrected extension references

aws-asg-terminate-random-instance/README.md, aws-asg-terminate-random-instance/aws-asg-terminate-random-instance-experiment.json
=> added aws asg terminate random instance

README.md
=> Updated directory nesting explanation

aws/ec2_stop_random_instance_in_az/README.md, aws/ec2_stop_random_instance_in_az/ec2_stop_random_instance_in_az_experiment.json
=> add stop random ec2 instance in availablity zone

ec2_restart_instance_by_filter_and_az/README.md, ec2_restart_instance_by_filter_and_az/ec2_restart_instance_by_filter_and_az.json
=> added restart instance by filter and az experiment

aws/ec2_stop_instance_by_filter_state_running_by_instance_id/README.md, aws/ec2_stop_instance_by_filter_state_running_by_instance_id/ec2_stop_instance_by_filter_state_running_by_instance_id.json
=> add ec2 stop instance with filter

aws/ec2_terminate_random_instance_in_az/README.md, aws/ec2_terminate_random_instance_in_az/ec2_terminate_random_instance_in_az.json
=> add ec2 terminate random instance experiment

aws/ec2_start_stop_instance_with_state_tolerance/README.md, aws/ec2_start_stop_instance_with_state_tolerance/ec2_start_stop_instance_with_state_tolerance.json
Signed-off-by: Sylvain Hellegouarch <sh@defuze.org>
=> Add rich tolerance check on AWS responses

kubernetes/game_day_drain_named_node/README.md, kubernetes/game_day_drain_named_node/game_day_setup.json, kubernetes/game_day_drain_named_node/game_day_teardown.json
=> Added Game Day style experiment

azure/aks_stop_random_node/README.md, kubernetes/delete_named_node/README.md, kubernetes/delete_named_node/delete _named_node_exeriment.json, kubernetes/delete_random_node/README.md, kubernetes/delete_random_node/delete_random_node_experiment.json, kubernetes/drain_node/README.md, kubernetes/drain_node/drain_node_experiment.json
=> remove references to redundant variable POD LABEL

azure/aks_stop_random_node/README.md, kubernetes/kill_microservice/README.md
=> Corrected URLs

aws/OpsWorks/ow_ec2_auto_heal_single_instance_service/README.md, aws/OpsWorks/ow_ec2_auto_heal_single_instance_service/ow_ec2_auto_heal_single_instance_service.json
=> created experiment for single instance auto heal with ops works

kubernetes/kill_pod_by_label/README.md, kubernetes/kill_pod_by_label/kill_pod_by_label_experiment.json
=> add kill pod by label experiment

local/url-responds/README.md, local/url-responds/url-responds.json
=> added url-responds experiment

README.md
=> Added chaos validate advice

toxiproxy/introduce_latency/introduce_latency_experiment.json
=> Moved rollback to only be in rollback section

local/url-responds/url-responds.json
=> echo out the url in the last step of url-responds

local/litmus-chaos-turbulenace/README.md, local/litmus-chaos-turbulenace/chaosengine.yaml, local/litmus-chaos-turbulenace/experiment.json
=> add an experiment that uses litmus chaos to inject turbulence
